"""
Shared State Definition for the Multi-Agent System

This module defines the TypedDict that represents the shared state
passed between agents in the LangGraph workflow.
"""

from typing import TypedDict, List, Dict, Any, Optional, Annotated
from langchain_core.messages import BaseMessage
import operator


def add_messages(left: List[BaseMessage], right: List[BaseMessage]) -> List[BaseMessage]:
    """Reducer function to accumulate messages."""
    return left + right


class AgentState(TypedDict):
    """
    Shared state that flows through the multi-agent workflow.
    
    Attributes:
        company_name: The target company to analyze
        messages: Conversation history for memory (accumulates via reducer)
        news_data: List of news articles collected by Data Collector agent
        stock_data: Stock performance metrics collected by Data Collector agent
        analysis: Market analysis generated by Analyst agent
        risk_factors: Risk assessment generated by Analyst agent
        final_report: Combined summary report
        current_agent: Which agent is currently active
        error: Any error messages
    """
    company_name: str
    messages: Annotated[List[BaseMessage], add_messages]
    news_data: Optional[List[Dict[str, Any]]]
    stock_data: Optional[Dict[str, Any]]
    analysis: Optional[str]
    risk_factors: Optional[List[str]]
    final_report: Optional[str]
    current_agent: Optional[str]
    error: Optional[str]


def create_initial_state(company_name: str) -> AgentState:
    """
    Create an initial state for a new workflow run.
    
    Args:
        company_name: The company to analyze
        
    Returns:
        Initialized AgentState
    """
    return AgentState(
        company_name=company_name,
        messages=[],
        news_data=None,
        stock_data=None,
        analysis=None,
        risk_factors=None,
        final_report=None,
        current_agent=None,
        error=None
    )
